# =========================================
# RS MobStand Configuration
# RS MobStand by Big_Pappa
# =========================================

config-version: 1


##########################################################
# Plugin Settings                                        #
##########################################################

# How often MobStands scan for mobs. Measured in ticks.
# 20 ticks = 1 second
scan-interval: 1200

# Default gravity state for new MobStands.
# true = Stand will fall until sitting on top of a block
# false = Stand will not fall if block below it is broken.
default-gravity: true

# Damage dealt to mobs.
damage-amount: 1000.0


##########################################################
# Scan Settings                                          #
#  Recommended maximum radius:                           #
#  32 for normal servers                                 #
#  48 for large/high-performance servers                 #
##########################################################

# Default radius new MobStands begin with.
default-scan-radius: 10

# Maximum radius players may set their MobStand to.
# Recommended maximum radius:
# 32 for normal servers
# 48 for large/high-performance servers
# Excessive values may impact performance heavily.
max-player-scan-radius: 32


##########################################################
# Stand Count Settings                                   #
##########################################################

# Maximum number of stands a player may place at one time.
# 0 = Unlimited
max-stands-per-player: 5

# Maximum number of stands that may be placed on the server at one time.
# 0 = Unlimited
max-total-stands: 200


##########################################################
# Settings below are for leaving mobs alive by default.  #
##########################################################

# Default setting when new stands are created.
default-leave-alive: 2

# Minimum amount users may set their stands to leave alive each
# scan and kill cycle.  NOTE: Named mobs DO NOT count as the
# RS Mob Stand ignores those completely.
min-leave-alive: 0

# Minimum amount users may set their stands to leave alive each
# scan and kill cycle.  NOTE: Named mobs DO NOT count as the
# RS Mob Stand ignores those completely.
max-leave-alive: 30


##########################################################
# Debugging                                              #
# Debugging options below this line are intended for     #
# development/testing and should be left disabled on     #
# production servers.                                    #
##########################################################

debug:
  enabled: false # Override all options below.

  logging:
    performance: true # Enables performance log entries
    entity-kills: true # Adds kill count to performance entries (Requires performance: true)

  performance:
    warning-ms: 100.0
    summary-interval-seconds: 300
