# =========================================
# RS MobStand Adult Mob Settings
# =========================================
# Add as many as you like. The menus will
# Center, add rows, and pagenate them
# automatically.
# =========================================

#==========================================
#  available items
# icon:  icon that will show for that mob in the menu
# enabled-by-default: wether or not will be killed by default
# kill-all: true Kills all these mob types regardless of user settings
# - Named mobs will still be ignored
#================================================================
# Kills all these mob types regardless of user settings
# kill-all: true
# - Named mobs will still be ignored
#================================================================
adult-mobs:

  BLAZE:
    icon: BLAZE_ROD
    enabled-by-default: true
    # true: Stand will kill all regardless of settings.
    # false: (or not existing for mob) will follow players setting.
    # Ignores per-stand settings.
    kill-all: false
  CAVE_SPIDER:
    icon: SPIDER_EYE
    enabled-by-default: true

  CHICKEN:
    icon: FEATHER
    enabled-by-default: true

  COW:
    icon: LEATHER
    enabled-by-default: true

  CREEPER:
    icon: GUNPOWDER
    enabled-by-default: true

  DROWNED:
    icon: COPPER_INGOT
    enabled-by-default: true

  ENDERMAN:
    icon: ENDER_PEARL
    enabled-by-default: true

  GHAST:
    icon: GHAST_TEAR
    enabled-by-default: true

  GUARDIAN:
    icon: PRISMARINE_SHARD
    enabled-by-default: true

  HOGLIN:
    icon: PORKCHOP
    enabled-by-default: true

  HUSK:
    icon: ROTTEN_FLESH
    enabled-by-default: true

  MAGMA_CUBE:
    icon: MAGMA_CREAM
    enabled-by-default: true

  PHANTOM:
    icon: PHANTOM_MEMBRANE
    enabled-by-default: true

  PIG:
    icon: PORKCHOP
    enabled-by-default: true

  PIGLIN:
    icon: GOLD_NUGGET
    enabled-by-default: true

  RABBIT:
    icon: RABBIT_HIDE
    enabled-by-default: true

  SHEEP:
    icon: WHITE_WOOL
    enabled-by-default: true

  SHULKER:
    icon: SHULKER_SHELL
    enabled-by-default: true

  SILVERFISH:
    icon: STONE
    enabled-by-default: true

  SKELETON:
    icon: BONE
    enabled-by-default: true

  SLIME:
    icon: SLIME_BALL
    enabled-by-default: true

  SPIDER:
    icon: STRING
    enabled-by-default: true

  WITCH:
    icon: GLASS_BOTTLE
    enabled-by-default: true

  ZOGLIN:
    icon: ROTTEN_FLESH
    enabled-by-default: true

  ZOMBIE:
    icon: ROTTEN_FLESH
    enabled-by-default: true

  ZOMBIE_VILLAGER:
    icon: EMERALD
    enabled-by-default: true

  ZOMBIFIED_PIGLIN:
    icon: GOLD_INGOT
    enabled-by-default: true