# =========================================
# RS MobStand baby Mob Settings
# =========================================
# Add as many as you like. The menus will
# Center, add rows, and pagenate them
# automatically.
# =========================================

#==========================================
#  available items
# icon:  icon that will show for that mob in the menu
# enabled-by-default: wether or not will be killed by default
# kill-all: Kills all these mob types regardless of user settings
# - Named mobs will still be ignored
#================================================================

baby-mobs:

  CHICKEN:
    icon: FEATHER
    enabled-by-default: false
    # true: Stand will kill all regardless of players settings.
    # false: (or not existing for mob) will follow players setting.
    # Ignores per-stand settings.
    kill-all: false

  COW:
    icon: LEATHER
    enabled-by-default: false

  DROWNED:
    icon: COPPER_INGOT
    enabled-by-default: true

  HOGLIN:
    icon: PORKCHOP
    enabled-by-default: true

  HUSK:
    icon: ROTTEN_FLESH
    enabled-by-default: true

  PIG:
    icon: PORKCHOP
    enabled-by-default: false

  PIGLIN:
    icon: GOLD_NUGGET
    enabled-by-default: true

  RABBIT:
    icon: RABBIT_HIDE
    enabled-by-default: false

  SHEEP:
    icon: WHITE_WOOL
    enabled-by-default: false

  ZOGLIN:
    icon: ROTTEN_FLESH
    enabled-by-default: true

  ZOMBIE:
    icon: ROTTEN_FLESH
    enabled-by-default: true

  ZOMBIE_VILLAGER:
    icon: EMERALD
    enabled-by-default: true

  ZOMBIFIED_PIGLIN:
    icon: GOLD_INGOT
    enabled-by-default: true
